FROM python:3.11-slim

COPY --from=eclipse-temurin:21-jre /opt/java/openjdk /opt/java/openjdk
ENV JAVA_HOME=/opt/java/openjdk
ENV LANG=C.UTF-8
ENV PATH=/opt/java/openjdk/bin:$PATH
RUN update-alternatives --install /usr/bin/java java /opt/java/openjdk/bin/java 1

# --- Системные пакеты ---
RUN apt-get update && apt-get install -y --no-install-recommends \
    wrk bzip2 curl unzip xz-utils binutils fontconfig libfreetype6 \
    ca-certificates p11-kit git wget graphviz graphviz-dev python3-dev build-essential \
    && rm -rf /var/lib/apt/lists/*

# --- Terraform  ---
ARG TARGETARCH
RUN case "${TARGETARCH}" in \
        "amd64")  TF_ARCH=amd64 ;; \
        "arm64")  TF_ARCH=arm64 ;; \
        *)        TF_ARCH=amd64 ;; \
    esac && \
    wget -q "https://hashicorp-releases.yandexcloud.net/terraform/1.10.5/terraform_1.10.5_linux_${TF_ARCH}.zip" -O /tmp/terraform.zip && \
    unzip -q /tmp/terraform.zip -d /usr/local/bin && \
    rm /tmp/terraform.zip && \
    chmod +x /usr/local/bin/terraform

# --- Java CA certs  ---
RUN set -eux; \
    { echo '#!/usr/bin/env bash'; echo 'set -Eeuo pipefail'; \
      echo 'trust extract --overwrite --format=java-cacerts --filter=ca-anchors --purpose=server-auth "$JAVA_HOME/lib/security/cacerts"'; \
    } > /etc/ca-certificates/update.d/docker-openjdk && \
    chmod +x /etc/ca-certificates/update.d/docker-openjdk && \
    /etc/ca-certificates/update.d/docker-openjdk && \
    find "$JAVA_HOME/lib" -name '*.so' -exec dirname '{}' ';' | sort -u > /etc/ld.so.conf.d/docker-openjdk.conf && \
    ldconfig

# --- Python зависимости  ---
COPY requirements/base.txt /opt/structurizr_backend/requirements/base.txt
RUN pip install --no-cache-dir -r /opt/structurizr_backend/requirements/base.txt && \
    rm -rf /root/.cache/pip

# --- Certs и Structurizr CLI (нужны для keytool до копирования всего кода) ---
COPY certs /opt/structurizr_backend/certs
COPY certs/*.crt /usr/local/share/ca-certificates/
COPY build /usr/local/structurizr-cli
RUN chmod +x /usr/local/structurizr-cli/structurizr.sh && \
    keytool -importcert -file /opt/structurizr_backend/certs/Vimpelcom_InternalCA_G2.crt -alias Vimpelcom_InternalCA_G2 -storepass changeit -noprompt -trustcacerts -cacerts && \
    keytool -importcert -file /opt/structurizr_backend/certs/Vimpelcom_RootCA_G2.crt -alias Vimpelcom_RootCA_G2 -storepass changeit -noprompt -trustcacerts -cacerts && \
    keytool -importcert -file /opt/structurizr_backend/certs/apps.yd-m6-kt22.vimpelcom.ru.crt -alias apps.yd-m6-kt22.vimpelcom.ru -storepass changeit -noprompt -trustcacerts -cacerts && \
    keytool -importcert -file /opt/structurizr_backend/certs/vega.vimpelcom.ru.crt -alias vega.vimpelcom.ru -storepass changeit -noprompt -trustcacerts -cacerts && \
    update-ca-certificates

# --- Исходный код  ---
COPY . /opt/structurizr_backend

WORKDIR /opt/structurizr_backend
ENTRYPOINT ["/usr/bin/bash"]
